### ISSUE TITLE
Need some clarification on dependencies and build instructions

### ISSUE THREAD

**Issue by dljsjr** [robotology-playground/ihmc-ors-yarp#14]
Hey there,

I'm trying to get an environment up and running to start the tests on this (I'm running a little behind my original projection because some other stuff came up) and I'm having issues with the build.

I was going to get up and running on a 14.04 test environment since we usually support both 14.04 and 16.04 for our Linux releases. The first issue I've run in to is that the CMake version that comes w/ 14.04 is too low, as the minimum version in the CMakeLists.txt is 3.5.

Next, I received an error that my YARP installation was the wrong version:

```
CMake Error at CMakeLists.txt:10 (find_package):
  Could not find a configuration file for package "YARP" that is compatible
  with requested version "2.3.70".

  The following configuration files were considered but not accepted:

    /usr/lib/x86_64-linux-gnu/YARP/YARPConfig.cmake, version: 2.3.66
```

I am using the YARP installation instructions for Trusty from here: http://www.yarp.it/install_yarp_linux.html

It's also unclear if the `asio` that comes w/ 14.04 (libasio-dev) is suitable (haven't gotten that far in the build yet). Related, should we use the boost or non-boost configuration of `asio`?

I think maybe the question I should be asking is: Should I target 16.04 for more up-to-date packages or should I grab a newer CMake and build YARP from source so that we can target 14.04?

**Comment by traversaro** [comment]
The latest versions of YARP is not officially supported on Trusty (see https://github.com/robotology/QA/issues/173), and this is the reason why the last binaries available on Trusty are the version 2.3.66 . 
However, we are using Trusty on a lot of CI based on Travis, so YARP is actually working fine on Ubuntu 14.04, the only necessary trick is to install the `cmake3` package from the official repositories (no need for PPA or third-party repos).

Indeed, in the Travis CI configuration of this repo we are using trusty : https://github.com/robotology-playground/ihmc-ors-yarp/blob/master/.travis.yml , so I think (at least for compiling, we are not running any test in Travis) that the `libasio-dev` available in Trusty should be ok. 

> Related, should we use the boost or non-boost configuration of asio?

We are using the non-boost configuration of `asio` . However, I just noticed that we are not defining `ASIO_STANDALONE` (https://think-async.com/Asio/AsioStandalone) anywhere, so it is possible that we are implicitly using some Boost parts, and the compilation could fail if the boost packages are not available. However this should be solved by just adding a `add_definitions(-DASIO_STANDALONE)` in the CMake build.

**Comment by dljsjr** [comment]
@traversaro so I should be able to just use `cmake3` and build YARP from source and I should be good to go?

**Comment by traversaro** [comment]
Yes.

**Comment by dljsjr** [comment]
Okay I think I'm in good shape. I just want to confirm that I have a properly running sim (haven't tried sending messages yet). I don't believe I have any errors.

1. Install all required packages
2. In a terminal: `yarpserver`
3. In another terminal: `gazebo <path>/icub.world`
4. In another terminal: `cd robots/icubGazeboSim && yarprobotinterface --config launch-bridgeihmcors-sim.xml`

From here I should be able to send DDS messages to the iCub simulation, yes? yarpserver seems to indicate that the bridge is online and the yarprobotinterface is reporting that it is "running happily" so I think I'm good to go...

**Comment by francesco-romano** [comment]
Hi @dljsjr 
Yes, I think you are doing everything correctly.

Before sending messages, you can try to read the feedback from the robot (until https://github.com/robotology-playground/ihmc-ors-yarp/issues/9 and #8 aren't solved, only joints information)
