### ISSUE TITLE
Not able to receive UDP RobotFeedback

### ISSUE THREAD

**Issue by dljsjr** [robotology-playground/ihmc-ors-yarp#17]
Hey folks,

I have everything up and running but when I start everything up (yarpserver, gazebo, and yarprobotinterface with the ihmc-ors configuration) I don't receive datagrams from our end.

For a quick note on my setup, I'm running the Gazebo/YARP stack in a Linux VM, and I'm trying to receive from my macOS Host with a private network between them. I updated the IP address for feedback in the XML. I have our side configured for a blocking receive and I never get a datagram in. Additionally, when I run `nettop` on my Mac I see no incoming UDP traffic and when I run `netstat -nupc` on the Linux guest I see no outgoing UDP traffic destined for the IP and port that I put in to the XML.

Any help here is greatly appreciated!

**Comment by lornat75** [comment]
Hi @dljsjr,
these instructions may help you check sanity of your network/linux without yarp, so we can narrow down the next debugging actions:

http://www.yarp.it/yarp_cluster.html

**Comment by traversaro** [comment]
@dljsjr  I have a mac, tomorrow I will try to replicate your setup and your problem.

**Comment by dljsjr** [comment]
@lornat75 I have already verified that the two can talk to each other over UDP. I went ahead and installed iperf to run the tests in your wiki and those also work.

@traversaro I don't think networking is an issue. When I run the IHMC ORS YARP Bridge inside the linux guest, and then use `netstat` to monitor outgoing UDP traffic, I don't see anything at all (except the occasional zeroconf/Bonjour discovery packet).

**Comment by dljsjr** [comment]
If it matters, I'm still on Ubuntu Trusty for packages installed from apt-get and these are the hashes I'm using for the stuff I had to build from source:

YARP: robotology/yarp@fbfbb2631a5962ecd61274b8272ae1d8801adff9

gazebo-yarp-plugins: robotology/gazebo-yarp-plugins@54c58728a27ff77f80ae2d7d571a0c383e0d9c42

icub-gazebo: robotology/icub-gazebo@ab22fdc34c0a9faa6f72428c2abdb6afc3145872

IHMC ORS YARP: robotology-playground/ihmc-ors-yarp@5ebb9bd64a19faacd429c7155147e88d8e771dbe

**Comment by traversaro** [comment]
Thanks, I will use a Trusty virtual machine to check if I get anything strange.

**Comment by dljsjr** [comment]
Well… it just started working. With no changes to your code or mine. So that's reassuring.

It seems to be flakey. Sometimes I get data reliably, other times I get nothing.

**Comment by dljsjr** [comment]
Looks like this was a huge red herring and not networking related at all. It was a deserialization issue disguised as a blocking receive because of threading on my end.

eProsima recently made a change to the way they store their CDR header (encapsulation) where it is now part of the core payload so our deserializer looks for that, even though it's not strictly required to be a valid message. So we just have to pad the receiving buffer with the defaults before we deserialize your datagrams.
