### ISSUE TITLE
Understand how to implement the joint control law expected by IHMC-ORS 

### ISSUE THREAD

**Issue by traversaro** [robotology-playground/ihmc-ors-yarp#3]
Original discussion, based on the message  https://github.com/robotology-playground/ihmc-ors-yarp/blob/master/idl/robotDesired.idl .

@traversaro : 
> Based on the JointDesired structure, I imagine that you would like the actual torque setpoint for the low-level torque regulator to be given by an Impedance such as:
τᵣ = τ_d + k_p*( q_d - q_m ) + k_d*( q̇_d - q̇_m )
We have a low-level "Control Mode" implementing something similar, but it will need some modifications to be used in this way. Do you frequently use k_p and k_d different from zero? If this is not the case, then it would be easier for us to just use the classical torque control mode with no impedance terms, and implement the impedance at "high-level" (still in the robot onboard pc, but not at the motor controlboard level).

@georgwi : 
> This is also robot dependent for us. In Atlas the torque control is not good enough for the balancing to work. So we use a mix of desired torque and position/velocity. Ideally we would have only torque control but as Jesper said for most robots we add some artificial damping or similar at the joint control level. I am fine with doing this at a higher level as long as this does not reduce stability. I imagine we would want to run the additional damping (non-zero k_d in your control law) at a high loop rate?

**Comment by traversaro** [comment]
My original plan was to implement the control law τᵣ = τ_d + k_p*( q_d - q_m ) + k_d*( q̇_d - q̇_m ) using the ControlMode PositionDirect and the InteractionMode Compliant (see http://wiki.icub.org/images/c/cf/ICub_Control_Modes_1_1.pdf), but then I realized some problems: 
* Using this control modality, you can send the desired position value q_d , but not (independently) the desired joint velocity q̇_d 
* The gains k_p and k_d are not meant to changed at each control loop, i.e. changing them takes some time. 
* If the gravity compensation modality of `wholebodydynamics` is enabled, the control model is `VOCAB_CM_POSITION_DIRECT` and the interaction mode is `VOCAB_INTERACTION_COMPLIANT`, then the `wholebodydynamics` evice sets the τ_d to be the gravity compensation terms, and there is not runtime way of disabling this. 

Given that solving these issues would be complicated, at least initially I would go for implementing the control law directly in the `bridge_ihmc_ors` YARP device. One thing that it  can be easily done is to have the control loop run faster then the period with which sensor messages are transmitted to the IHMC-ORS controller (ideally this control loop should run at the same period of the communication between the EMS and the yarprobotinterface). 

Slightly related: to increase the damping in the robot, we typically decrease the viscous friction compensation term in the low level joint torque control loop: this has the disadvantage of breaking the independence between the torque control loop and the higher level controller, but has the advantage that the "natural" damping provided by the system cannot incur in instability created by the delay of the controller.

**Comment by traversaro** [comment]
cc @gabrielenava

**Comment by fiorisi** [comment]
Implemented in the current prototype.
