### ISSUE TITLE
Understand how the interaction between the yarprobointerface and the IHMC-ORS controller will work

### ISSUE THREAD

**Issue by traversaro** [robotology-playground/ihmc-ors-yarp#4]
Original discussion: 

@traversaro : 
> Our robot starts independently from any kind of client (including the eventual ihmc-based client) and at startup reaches a given "home" position while using a low-level trajectory generaton + position PID controller , and then waits for new references values or for a change in "Control Mode" (see http://wiki.icub.org/images/c/cf/ICub_Control_Modes_1_1.pdf for an in-depth discussion). How do you expect the robot to handle the switching On/Off of the IHMC controller? Do you expect to change the enabled flag of the JointDesired structure while the IHMC controller is running? What is the expected behaviour of the joint in this case?

@georgwi 
> That is very robot dependent for us right now. For Atlas we use position control to move the robot into a starting configuration. We then switch on the whole body control loop once we detect that the feet are loaded after the robot has been put on the ground and transition the whole robot to torque control. For other robots we implemented different ways of doing this. We can implement a state machine on our side for placing the robot on the ground under position control and then switching to whole body torque control. As long as we can set the joint control mode through the interface we can use the state machine on our side. I think adding the joint control mode to the joint desired structure would be good. Here is how it could work:
>  - iCub turns on and goes to home configuration with IIT controller
>  - We start the IHMC controller with in hold joint positions state and take over joint control (position mode)
>  - We manually trigger the IHMC state machine to move to some starting configuration and place the robot on the ground (position mode)
>  - We manually trigger the IHMC state machine to go to whole body balancing (torque mode)

**Comment by traversaro** [comment]
cc @gabrielenava

**Comment by traversaro** [comment]
For the first prototype I will push today, the super-simple logic of the bridge is described by the following FSM: 
![state](https://user-images.githubusercontent.com/1857049/32063969-e05ff15c-ba78-11e7-9f20-5cb08d86f54d.png)

The bridge starts in the OFF state. As soon as it receives a RobotDesireds message, it switches to the ON state. While entering in the ON state, it switches all the YARP control modes of the joint handled by the bridge to `VOCAB_CM_TORQUE`.

While the bridge is in the ON state, it sends desired torques based on the control law specified in https://github.com/robotology-playground/ihmc-ors-yarp/issues/3, using data received from the RobotDesireds messages and the feedback received from the robot.  

Once more then 0.1 second pass without receiving any RobotDesireds message, the bridge switches back to the OFF state, and it switches back all the joint to the YARP control mode `VOCAB_CM_POSITION`.

The handling of the `enabled` flag in the RobotDesireds message and more advanced logic can be added in the future.

**Comment by traversaro** [comment]
New FSM for the joint state: 
![ors-bridge-fsm 1](https://user-images.githubusercontent.com/1857049/32371398-f7be7274-c090-11e7-8bc7-fd539845c8cf.png)

**Comment by fiorisi** [comment]
Implemented in the current prototype.
