### ISSUE TITLE
How to communicate to Java data ordering and number of devices

### ISSUE THREAD

**Issue by gabrielenava** [robotology-playground/ihmc-ors-yarp#5]
There are a couple of info it may be useful not to hard-code, but instead try to get/provide them at startup (assuming they are not changing during execution), to be sure that the Java software is reading correctly the data coming from Yarp. The required info are:

- Data ordering, e.g. : joints, FT data, IMU data ordering.

Also these information may be avoided to be hard-coded:

- Number of FT sensors and IMUs on the robot.

This issue is for discussing how to provide these info without overloading the communication between Yarp and Java

**Comment by gabrielenava** [comment]
cc @fiorisi @traversaro @francesco-romano

**Comment by traversaro** [comment]
In the draft* message definition https://github.com/robotology-playground/ihmc-ors-yarp/blob/master/idl/robotFeedback.idl#L45 @jespersmith originally put the comment: 
> Joint order agreed beforehand and hard coded in first version

Given this comment, I think that (at least initially) the ihmc side of the controller would hardcode those list, so I think we can avoid think about this aspects (and eventual "configuration" messages) until we have a working prototype with "hardcoded" lists. 

 \* **Note:** I just copied the `.idl` messages in the repo from the original proposal by @jespersmith and they should be revised as development continues.

**Comment by gabrielenava** [comment]
If I understood correctly in the end we went for hardcoding the list of devices, so we can close this issue.
