### ISSUE TITLE
Publish ForceTorque sensor measurements

### ISSUE THREAD

**Issue by traversaro** [robotology-playground/ihmc-ors-yarp#9]

**Comment by traversaro** [comment]
As discussed in https://github.com/loc2/element_icub-at-ihmc/issues/37 , the most convenient information for the IHMC controller is not the measurement of the FT sensor, but rather the estimate of the sole contact force provided by wholeBodyDynamics. Unfortunately this information is not currently exposed using a C++ interface, so an appropriate interface should be developed. For the time being, the information can be directly read by bridge from YARP ports (this solution could introduce some jitter on the FT measurement, that will be eliminated when switching directly to the C++ interfaces).

**Comment by francesco-romano** [comment]
@traversaro if you want I can take care of providing FT measurements by bridging the YARP ports

**Comment by fiorisi** [comment]
Solved by this pull request https://github.com/robotology-playground/ihmc-ors-yarp/pull/15.
